source "https://rubygems.org"

gem "rake", "~> 10.3.1"
gem "chef", "~> 11.12.4"
gem "minitest", "~> 5.3.3"
gem "berkshelf", "~> 3.1.1"
gem "foodcritic", "~> 3.0.3"
gem "test-kitchen", "~> 1.2.1"
gem "kitchen-vagrant", "~> 0.15.0"
